In [37]:
import torch
import numpy as np
print(torch.__version__)

2.7.1+cpu


## Làm quen với tensor

### create tensor

In [31]:
data = [[1,2,3], [4,5,6], [7,8,9]]
x = torch.tensor(data, dtype=torch.float32)
print(x)
print(x.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])


In [44]:
np_data = np.array(data)
print(np_data.shape)
np_data = np_data.astype(np.float32)  # Ensure the numpy array is of type float32
y = torch.tensor(data, dtype=torch.float16)
print(y)
print(y.shape)
print(torch.equal(x, y))  # Check if the tensors are equal

(3, 3)
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float16)
torch.Size([3, 3])
True


In [45]:
x_one = torch.ones((3, 3), dtype=torch.float32)
print(x_one)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [52]:
x_ones = torch.ones_like(x)
print(x_ones)
z = torch.tensor([
    [1, 1, 1, 2, 3 , 4, 5, 6, 7, 8, 9],
    [1, 1, 1, 2, 3 , 4, 5, 6, 7, 8, 9],
    [1, 1, 1, 2, 3 , 4, 5, 6, 7, 8, 9]
])
z_ones = torch.ones_like(z, dtype=torch.float32)
print(z_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [53]:
x_rand = torch.rand_like(x, dtype=torch.float32)
print(x_rand)

tensor([[0.3905, 0.3797, 0.8998],
        [0.0939, 0.1304, 0.4645],
        [0.5955, 0.1943, 0.5377]])


In [54]:
x_zeros = torch.zeros_like(x, dtype=torch.float32)
print(x_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### slicing


In [55]:
tensor = torch.rand(4,4, dtype=torch.float32)
print(tensor)
print("first element:", tensor[0, 0])
print("last element:", tensor[-1, -1])
print("first row:", tensor[0, :])
print("last row:", tensor[-1, :])
print("first column:", tensor[:, 0])
print("last column:", tensor[:, -1])
tensor[:, 1] = 0  # Set the second column to zero
print("After setting second column to zero:")
print(tensor)
print("Shape of tensor:", tensor.shape)

tensor([[0.5007, 0.1181, 0.9164, 0.5304],
        [0.8427, 0.8907, 0.2444, 0.0753],
        [0.4247, 0.8589, 0.9274, 0.0688],
        [0.7416, 0.5967, 0.8142, 0.6673]])
first element: tensor(0.5007)
last element: tensor(0.6673)
first row: tensor([0.5007, 0.1181, 0.9164, 0.5304])
last row: tensor([0.7416, 0.5967, 0.8142, 0.6673])
first column: tensor([0.5007, 0.8427, 0.4247, 0.7416])
last column: tensor([0.5304, 0.0753, 0.0688, 0.6673])
After setting second column to zero:
tensor([[0.5007, 0.0000, 0.9164, 0.5304],
        [0.8427, 0.0000, 0.2444, 0.0753],
        [0.4247, 0.0000, 0.9274, 0.0688],
        [0.7416, 0.0000, 0.8142, 0.6673]])
Shape of tensor: torch.Size([4, 4])


### join 

In [57]:
t1 = torch.cat((tensor, tensor, tensor, tensor), dim=0)  # Concatenate along the first dimension
print("Concatenated tensor shape:", t1.shape)
print("Concatenated tensor:", t1)
t2 = torch.cat((tensor, tensor, tensor, tensor), dim=1)  # Concatenate along the second dimension
print("Concatenated tensor shape:", t2.shape)
print("Concatenated tensor:", t2)

Concatenated tensor shape: torch.Size([16, 4])
Concatenated tensor: tensor([[0.5007, 0.0000, 0.9164, 0.5304],
        [0.8427, 0.0000, 0.2444, 0.0753],
        [0.4247, 0.0000, 0.9274, 0.0688],
        [0.7416, 0.0000, 0.8142, 0.6673],
        [0.5007, 0.0000, 0.9164, 0.5304],
        [0.8427, 0.0000, 0.2444, 0.0753],
        [0.4247, 0.0000, 0.9274, 0.0688],
        [0.7416, 0.0000, 0.8142, 0.6673],
        [0.5007, 0.0000, 0.9164, 0.5304],
        [0.8427, 0.0000, 0.2444, 0.0753],
        [0.4247, 0.0000, 0.9274, 0.0688],
        [0.7416, 0.0000, 0.8142, 0.6673],
        [0.5007, 0.0000, 0.9164, 0.5304],
        [0.8427, 0.0000, 0.2444, 0.0753],
        [0.4247, 0.0000, 0.9274, 0.0688],
        [0.7416, 0.0000, 0.8142, 0.6673]])
Concatenated tensor shape: torch.Size([4, 16])
Concatenated tensor: tensor([[0.5007, 0.0000, 0.9164, 0.5304, 0.5007, 0.0000, 0.9164, 0.5304, 0.5007,
         0.0000, 0.9164, 0.5304, 0.5007, 0.0000, 0.9164, 0.5304],
        [0.8427, 0.0000, 0.2444, 0.0753, 0.8

### Inplace "_"

In [ ]:
# Các hàm có dấu _ thay đổi trực tiếp nội dung của tensor gốc, không tạo ra tensor mới.

x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print("Original tensor x:") 
print(x)
x.add_(1)  # Thêm 1 vào từng phần tử của tensor x
print("Tensor x after in-place addition:")
print(x)
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
z = x.add(1)  # Thêm 1 vào từng phần tử của tensor x, không thay đổi tensor gốc
print("Tensor x after out-of-place addition:")
print(x)
print("New tensor z after out-of-place addition:")
print(z)
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
x.add_(1, alpha=2)  # Thêm 2 vào từng phần tử của tensor x
print("Tensor x after in-place addition with alpha:")   
print(x)
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
x.add(1, alpha=2)  # Thêm 2 vào từng phần tử của tensor x, không thay đổi tensor gốc
print("Tensor x after out-of-place addition with alpha:")
print(x)
print("New tensor z after out-of-place addition with alpha:")
z = x.add(2, alpha=4)  # Thêm 2*4 vào từng phần tử của tensor x, không thay đổi tensor gốc
print(z)

Original tensor x:
tensor([[1., 2.],
        [3., 4.]])
Tensor x after in-place addition:
tensor([[2., 3.],
        [4., 5.]])
Tensor x after out-of-place addition:
tensor([[1., 2.],
        [3., 4.]])
New tensor z after out-of-place addition:
tensor([[2., 3.],
        [4., 5.]])
Tensor x after in-place addition with alpha:
tensor([[3., 4.],
        [5., 6.]])
Tensor x after out-of-place addition with alpha:
tensor([[1., 2.],
        [3., 4.]])
New tensor z after out-of-place addition with alpha:
tensor([[ 9., 10.],
        [11., 12.]])


# Các phép toán với tensor

## Phép cộng

In [58]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print("Tensor a:", a)
print("Tensor b:", b)
print("Element-wise addition:", a + b)

Tensor a: tensor([1, 2, 3])
Tensor b: tensor([4, 5, 6])
Element-wise addition: tensor([5, 7, 9])


In [59]:
c = a + b
d = torch.add(a, b)
e = torch.add(a, b, alpha=2)# 1+4*2, 2+5*2, 3+6*2
# alpha is a multiplier for the second tensor, b
# Uncommenting the next line will raise an error because alpha must be an integer
# f = torch.add(a, b, alpha=1.5) 
print ("c", c)
print ("d", d)
print ("e", e)  



c tensor([5, 7, 9])
d tensor([5, 7, 9])
e tensor([ 9, 12, 15])


## Phép trừ

In [60]:
# Tensor a: tensor([1, 2, 3])
# Tensor b: tensor([4, 5, 6])
print("a - b:", a - b)
i = torch.sub(a, b)
k = torch.sub(a, b, alpha=2)  # 1-4*2, 2-5*2, 3-6*2
# Uncommenting the next line will raise an error because alpha must be an integer
# l = torch.sub(a, b, alpha=1.5)  # 1-4*1.5, 2-5*1.5, 3-6*1.5
print("i:", i)
print("k:", k)  # k = a - b * 2

a - b: tensor([-3, -3, -3])
i: tensor([-3, -3, -3])
k: tensor([-7, -8, -9])


## Phép nhân

In [61]:
print("a * 3:", a * 3)

a * 3: tensor([3, 6, 9])


In [62]:
# Tensor a: tensor([1, 2, 3])
# Tensor b: tensor([4, 5, 6])
print("a*b:", a * b)
j = torch.mul(a, b)
l = torch.mul(a, b)  # 1*4*2, 2*5*2, 3*6*2
print("j:", j)
print("l:", l)  # l = a * b * 2

a*b: tensor([ 4, 10, 18])
j: tensor([ 4, 10, 18])
l: tensor([ 4, 10, 18])


## Phép chia

In [63]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 8, 6])
print("a / b:", a / b)
h = torch.div(a, b)

print("h:", h)  # h = a / b


a / b: tensor([0.2500, 0.2500, 0.5000])
h: tensor([0.2500, 0.2500, 0.5000])


In [64]:
# Chia làm tròn xuống
f = torch.floor_divide(a, b)
print("f:", f)  # f = a // b (integer division)
# Lấy phần dư (mod)
r = torch.remainder(a, b)
print("r:", r)  # r = a % b (remainder)
# Lấy phần dư (mod) với rounding_mode
g = torch.div(a, b, rounding_mode='trunc')  # 1//4, 2//8, 3//6
# rounding_mode='trunc' → Làm tròn về 0 (truncate)
# rounding_mode='floor' → Làm tròn xuống âm vô cực (floor)
print("g:", g)  # g = a // b (integer division)

f: tensor([0, 0, 0])
r: tensor([1, 2, 3])
g: tensor([0, 0, 0])


## Nhân hai ma trận

In [69]:
m1 = torch.tensor([[1, 2], [3, 4]])
m2 = torch.tensor([[5, 6], [7, 8]])
y1 = m1 @ m2.T  # Matrix multiplication of m1 and transpose of m2
y2 = m1.matmul(m2.T)  # Matrix multiplication using matmul method
y3 = torch.mm(m1, m2.T)  # Matrix multiplication using mm function
y4 = m1 @ m2  # Matrix multiplication of m1 and m2 (no transpose)
y5 = m1.matmul(m2)  # Matrix multiplication using matmul method (no transpose)
print("y4:", y4)  # y4 = m1 @ m2 (matrix multiplication without transpose)
print("y5:", y5)  # y5 = m1.matmul(m2) (matrix multiplication without transpose)
print("y1:", y1)  # y1 = a @ b.T (matrix multiplication)
print("y2:", y2)  # y2 = a.matmul(b.T) (matrix multiplication)
print("y3:", y3)  # y3 = torch.mm(a, b.T) (matrix multiplication)

y4: tensor([[19, 22],
        [43, 50]])
y5: tensor([[19, 22],
        [43, 50]])
y1: tensor([[17, 23],
        [39, 53]])
y2: tensor([[17, 23],
        [39, 53]])
y3: tensor([[17, 23],
        [39, 53]])


## SUM


In [72]:
print(a)
agg = torch.sum(a)  # Sum of all elements in tensor a
print("Sum of all elements in a:", agg)
agg_item = agg.item()  # Convert the sum to a Python number
print("Sum as Python number:", agg_item)

tensor([1, 2, 3])
Sum of all elements in a: tensor(6)
Sum as Python number: 6
